// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Hadir",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Hadir",
            targets: ["AppModule"],
            bundleIdentifier: "com.faridnahdi.Hadir",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Hadir needs microphone access to listen to doctor-patient conversations and generate real-time transcription for SOAP notes."),
                .speechRecognition(purposeString: "Hadir uses on-device speech recognition to transcribe doctor-patient conversations into SOAP notes in real-time.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources"
        )
    ]
)
